### ISSUE TITLE
Unable to open a PR

### ISSUE THREAD

**Issue by martynlanglands** [Williams-Dan/covidhelp#10]
Hey Dan,

My sister Emma was having an issue with your rake file so i've cloned the repo and tried to submit a PR but I have access denied. Would you be able to update your branch permissions please? 

If you create a Develop branch - I can submit a PR to that for testing.

Thanks,
Martyn

**Comment by Williams-Dan** [comment]
Hey Martyn,

If you fork the repository and submit your changes there you can open a PR for your changes into the upstream repository.
I have created a develop branch for if you'd be more comfortable submitting a PR there than master :) https://github.com/Williams-Dan/covidhelp/tree/develop

Thanks,
Dan

**Comment by martynlanglands** [comment]
> Hey Martyn,
> 
> If you fork the repository and submit your changes there you can open a PR for your changes into the upstream repository.
> I have created a develop branch for if you'd be more comfortable submitting a PR there than master :) https://github.com/Williams-Dan/covidhelp/tree/develop
> 
> Thanks,
> Dan

Hey Dan,

That's great - still having issues with the permissions on the develop branch.

> git branch --set-upstream-to=origin/develop feature/martynlanglands/update_ci

**Comment by Williams-Dan** [comment]
Hey Martyn,

You won't be able to use the new develop branch as upstream for your feature branch.
You will need to:
* Fork the repository (this creates a copy of covidhelp under your github account);
* Change the origin remote in git to point to your fork (`git remote set-url origin <url to your fork>`;
* Commit and push your changes setting the branch upstream to a branch on your fork (`git push --set-upstream origin feature/martynlanglands/update_ci `);
* Then on github open a pull request on your fork into the develop branch of mine;

You can read on how to fork a repo [here](https://help.github.com/en/github/getting-started-with-github/fork-a-repo#propose-changes-to-someone-elses-project) hope this helps :)

**Comment by martynlanglands** [comment]
Hey Dan,

Thanks - not a massive fan of forking but done it now. 

If you are on linkedin btw - fire me a request. :)

https://www.linkedin.com/in/martyn-langlands/

Thanks,
Martyn
